<script lang="ts">
	import './layout.css';
	import { ModeWatcher } from 'mode-watcher';
	import { page } from '$app/state';
	import { Toaster, toast } from '@tabeladev/tabelawebui';
	import { ToastType } from '$lib/enums/toast-type';
	import { pwaInfo } from 'virtual:pwa-info';
	import { getFlash } from 'sveltekit-flash-message';
	import ReloadPrompt from '$lib/components/ReloadPrompt.svelte';

	let { children } = $props();

	let webManifestLink = $derived(pwaInfo ? pwaInfo.webManifest.linkTag : '');

	const flash = getFlash(page);

	$effect(() => {
		const f = $flash;
		if (!f) return;

		if (f.type === ToastType.success) {
			toast.success(f.message);
		} else if (f.type === ToastType.error) {
			toast.error(f.message);
		} else if (f.type === ToastType.info) {
			toast.info(f.message);
		} else if (f.type === ToastType.warning) {
			toast.warning(f.message);
		}

		// Clear the flash after showing the toast so it does not fire again
		$flash = undefined;
	});
</script>

<svelte:head>
	<link rel="icon" href="/favicon.ico" sizes="48x48" />
	<link rel="apple-touch-icon" href="/apple-touch-icon-180x180.png" />
	<!-- eslint-disable-next-line svelte/no-at-html-tags -- generated by the plugin (virtual:pwa-info), not user input -->
	{@html webManifestLink}
</svelte:head>
<ModeWatcher lightClassNames={['light']} darkClassNames={['dark']} />
<Toaster />
<ReloadPrompt />
{@render children()}
