/// <reference path="./svelte-kit-worker.d.ts" />
// Wrapper around the worker generated by @sveltejs/adapter-cloudflare.
//
// The installed adapter version (@sveltejs/adapter-cloudflare@^7) only generates a
// `_worker.js` with `export default { fetch }` — there is no documented extension
// for adding other handlers (scheduled, queue, etc), see
// https://github.com/sveltejs/kit/issues/13692. Same pattern as TabelaCal:
// `wrangler.jsonc`'s `main` points to this wrapper, which re-exports the `fetch`
// generated by SvelteKit and adds `scheduled` on top.
//
// The adapter is configured (vite.config.ts: adapter({ config:
// 'wrangler.adapter.jsonc' })) to read a *separate* config from the real wrangler.jsonc,
// just to keep writing the generated worker to the default location
// (.svelte-kit/cloudflare/_worker.js) instead of overwriting this file —
// see comment in wrangler.adapter.jsonc.
//
// Intentionally outside `src/`: if it were inside, `svelte-check` would
// type-check the generated `_worker.js` transitively (a large, untyped Rollup
// bundle).
//
// `$lib` works here because `wrangler.jsonc` declares `alias: { "$lib":
// "./src/lib" }`, resolved by wrangler's esbuild (same idea as Vite's alias,
// but for the bundle wrangler generates from this `main`).
import server from '../.svelte-kit/cloudflare/_worker.js';
import { syncAllUsers } from '$lib/server/pluggy/sync';
import { generateMonthlyReports } from '$lib/server/reports/generate';

export default {
	fetch: server.fetch,
	/**
	 * @param {ScheduledController} event
	 * @param {Env} env
	 * @param {ExecutionContext} ctx
	 */
	async scheduled(event, env, ctx) {
		// wrangler.jsonc declares two crons: "0 6 * * *" (daily sync) and
		// "0 7 1 * *" (monthly report, day 1) — event.cron distinguishes which one fired.
		if (event.cron === '0 7 1 * *') {
			ctx.waitUntil(generateMonthlyReports(env));
		} else {
			ctx.waitUntil(syncAllUsers(env));
		}
	}
};
