// Ambient declaration for the '../.svelte-kit/cloudflare/_worker.js' import in
// entry.js. This file only exists after `vite build` (it is generated by
// @sveltejs/adapter-cloudflare via wrangler.adapter.jsonc — see comment in
// that file and in entry.js), so `svelte-check` cannot resolve it when run
// without a prior build (the normal `bun run check` flow, which should not
// depend on build output). This keeps the import typed without requiring
// the build.
// TS only consults ambiguous module declarations (fallback when the real
// resolution fails) for relative specifiers when the pattern has a wildcard —
// an exact declaration (without "*") is ignored for relative imports.
declare module '*.svelte-kit/cloudflare/_worker.js' {
	const worker: {
		fetch: (request: Request, env: Env, ctx: ExecutionContext) => Promise<Response>;
	};
	export default worker;
}
